name: Publish

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v2
    
    # RELEASE_TAG: v0.0.1
    # RELEASE_VERSION: 0.0.1
    - name: Set env
      run: |
        echo ::set-env name=RELEASE_TAG::$(echo ${GITHUB_REF:10})
        echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    
    - name: Install vsce
      run: |
        npm install -g vsce
      
    - name: Publish
      run: |
        vsce login ${{ secrets.VSCE_USER }}
        ${{ secrets.VSCE_TOKEN }}
        vsce publish ${RELEASE_VERSION} -p ${{ secrets.VSCE_TOKEN }}
    - name: Package
      